An exception occurred:

EXCEPTION:
<%= @exception.class.name %> in <%= @controller.controller_name %>#<%= @controller.action_name %>

ERROR:
<%= @exception.message %>

----------------
Request Overview
----------------
 * URL: <%= @request.protocol %><%= @host %><%= @request.request_uri %>
 * Parameters: <%= @request.parameters.inspect %>
 * Session ID: <%= @request.session.instance_variable_get(:@session_id).inspect %>
 * Session Data: <%= PP.pp(@request.session.instance_variable_get(:@data),"").gsub(/\n/, "\n  ").strip %>

 * Server : <%= `hostname`.chomp %>
 * Process: <%= $$ %>
 * Rails root: <%= @rails_root %>

 * Date/Time: <%= @time.to_s :full %>

---------------
Request Details
---------------
<% max = @request.env.keys.max { |a,b| a.length <=> b.length } -%>
<% @request.env.keys.sort.each do |key| -%>
 * <%= "%-*s: %s" % [max.length, key, @request.env[key].to_s.strip] %>
<% end -%>

---------
Backtrace
---------
<%= @backtrace.join("\n") %>